### ISSUE TITLE
package notes from "Check"

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HolyokeUrbanRenewal#14]
Despite several efforts on my part, the `HolyokeUrbanRenewal` package still has several notes.

Here's what is displayed when I run "Check":

```
❯ checking R code for possible problems ... NOTE
  select_building: no visible binding for global variable ‘block’
  select_building: no visible binding for global variable ‘parcel’
  Undefined global functions or variables:
    block parcel
```

I don't know how worried (if at all, we should be about this warning).

(Note: this takes several minutes given the large number of images in the package. I don't know of a workaround.)

**Comment by Casey308** [comment]
I think the first answer to this question, https://stackoverflow.com/questions/76242926/using-data-table-in-package-development-undefined-global-functions-or-variables, does a good job of explaining the issue, which I believe is the same issue occurring here. 

There seems to be a couple of "hacky" fixes to this issue, such as adding the following to the start of the function: 
`block <- parcel  <- NULL`

However, these all seem like just silencing the issue without changing anything, so I'm not sure it is what we would want to do, since it seems innocuous enough.

**Comment by nicholasjhorton** [comment]
Thanks for exploring this: I'm closing the issue for now.
